#cloud-config
users:
 - name: root
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBPEtofP0WfEKfFbTUBw8xwgEbUKxM1lvlApl2wvBtP8 root@diplom

disable_root: true
timezone: Europe/Moscow
repo_update: true
repo_upgrade: true

#нужна для ubuntu 20.04 apt

apt:
  preserve_sourses_list: true

packages:
  - wget
  - nginx

runcmd:
 - [sh, -c, "wget https://repo.zabbix.com/zabbix/6.5/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.5-1+ubuntu20.04_all.deb"]
 - [sh, -c, "sudo dpkg -i zabbix-release_6.5-1+ubuntu20.04_all.deb"]
 - [sh, -c, "sudo apt update"]
 - [sh, -c, "sudo apt install zabbix-agent2 zabbix-agent2-plugin-*"]
 - [systemctl, enable, nginx.service]
 - [systemctl, start, --no-block, nginx.service]
 - [sh, -c, "echo 'Welcome to web server - Nginx: zone a!'$(hostname | cut -d '.' -f 1 ) > /usr/share/nginx/html/index.html"]
 - [sh, -c, "echo $(ip  add ) >> /usr/share/nginx/html/index.html"]
 - [systemctl, restart, nginx.service]
 - [systemctl, restart, zabbix-agent2]
 - [systemctl, enable, zabbix-agent2]
