---

#- hosts: web-srv

- hosts: test

#  tasks:
#  - name: "Install package nginx"
#    apt: name=nginx update_cache=yes
#    sudo: yes
#  - name: "Starting service nginx"
#    service: name=nginx state=started
#    sudo: yes

  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  remote_user: root
  roles:
    - nginx
